{% set name = "biofkit" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/biofkit-{{ version }}.tar.gz
  sha256: 858459b0982fce363c98ef553b4f4101ae70ccc8906d28d33917d81f4909a8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10

test:
  imports:
    - biofkit
  commands:
    - pip check
  requires:
    - pip

about:
  summary: With biofkit you can deal with pdb file (extract sequence, atom information and so on) very easily. And pairwise alignment function is now online.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Chou-Uken
    - PQLW
